# Generated by Django 6.0.6 on 2026-06-03 22:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('options', models.JSONField(verbose_name='Варианты ответов и метаданные')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный ID теста')),
                ('slug', models.CharField(max_length=50, null=True, unique=True, verbose_name='Уникальный слаг')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test_images/', verbose_name='Изображение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Изображение к вопросу',
                'verbose_name_plural': 'Изображения к вопросам',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.testsuite', verbose_name='Тест'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test_suite', 'number')},
        ),
    ]
